/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocuViewareSaveParameters
 */
public class DocuViewareSaveParametersTest {
    private final DocuViewareSaveParameters model = new DocuViewareSaveParameters();

    /**
     * Model tests for DocuViewareSaveParameters
     */
    @Test
    public void testDocuViewareSaveParameters() {
        // TODO: test DocuViewareSaveParameters
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'controlId'
     */
    @Test
    public void controlIdTest() {
        // TODO: test controlId
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'pageRange'
     */
    @Test
    public void pageRangeTest() {
        // TODO: test pageRange
    }

}
