/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.FontStyle;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Font
 */
public class FontTest {
    private final Font model = new Font();

    /**
     * Model tests for Font
     */
    @Test
    public void testFont() {
        // TODO: test Font
    }

    /**
     * Test the property 'fontStyle'
     */
    @Test
    public void fontStyleTest() {
        // TODO: test fontStyle
    }

    /**
     * Test the property 'familyName'
     */
    @Test
    public void familyNameTest() {
        // TODO: test familyName
    }

}
