/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DrawableContentLayoutParameters;
import org.openapitools.client.model.PdfTextParameters;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FreeTextAnnotationParameters
 */
public class FreeTextAnnotationParametersTest {
    private final FreeTextAnnotationParameters model = new FreeTextAnnotationParameters();

    /**
     * Model tests for FreeTextAnnotationParameters
     */
    @Test
    public void testFreeTextAnnotationParameters() {
        // TODO: test FreeTextAnnotationParameters
    }

    /**
     * Test the property 'annotationLayout'
     */
    @Test
    public void annotationLayoutTest() {
        // TODO: test annotationLayout
    }

    /**
     * Test the property 'textParameters'
     */
    @Test
    public void textParametersTest() {
        // TODO: test textParameters
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'showBorder'
     */
    @Test
    public void showBorderTest() {
        // TODO: test showBorder
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

}
