/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetDocumentPreviewParameters
 */
public class GetDocumentPreviewParametersTest {
    private final GetDocumentPreviewParameters model = new GetDocumentPreviewParameters();

    /**
     * Model tests for GetDocumentPreviewParameters
     */
    @Test
    public void testGetDocumentPreviewParameters() {
        // TODO: test GetDocumentPreviewParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'thumbnailWidth'
     */
    @Test
    public void thumbnailWidthTest() {
        // TODO: test thumbnailWidth
    }

    /**
     * Test the property 'thumbnailHeight'
     */
    @Test
    public void thumbnailHeightTest() {
        // TODO: test thumbnailHeight
    }

    /**
     * Test the property 'thumbnailBackgroundColor'
     */
    @Test
    public void thumbnailBackgroundColorTest() {
        // TODO: test thumbnailBackgroundColor
    }

    /**
     * Test the property 'thumbnailFitToPageSize'
     */
    @Test
    public void thumbnailFitToPageSizeTest() {
        // TODO: test thumbnailFitToPageSize
    }

}
