/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ContentSize;
import org.openapitools.client.model.LineAnnotationEndingStyle;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LineAnnotationParameters
 */
public class LineAnnotationParametersTest {
    private final LineAnnotationParameters model = new LineAnnotationParameters();

    /**
     * Model tests for LineAnnotationParameters
     */
    @Test
    public void testLineAnnotationParameters() {
        // TODO: test LineAnnotationParameters
    }

    /**
     * Test the property 'lineStartX'
     */
    @Test
    public void lineStartXTest() {
        // TODO: test lineStartX
    }

    /**
     * Test the property 'lineStartY'
     */
    @Test
    public void lineStartYTest() {
        // TODO: test lineStartY
    }

    /**
     * Test the property 'lineEndX'
     */
    @Test
    public void lineEndXTest() {
        // TODO: test lineEndX
    }

    /**
     * Test the property 'lineEndY'
     */
    @Test
    public void lineEndYTest() {
        // TODO: test lineEndY
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'lineStartStyle'
     */
    @Test
    public void lineStartStyleTest() {
        // TODO: test lineStartStyle
    }

    /**
     * Test the property 'lineEndStyle'
     */
    @Test
    public void lineEndStyleTest() {
        // TODO: test lineEndStyle
    }

    /**
     * Test the property 'showContent'
     */
    @Test
    public void showContentTest() {
        // TODO: test showContent
    }

    /**
     * Test the property 'lineWidth'
     */
    @Test
    public void lineWidthTest() {
        // TODO: test lineWidth
    }

    /**
     * Test the property 'absoluteAnnotationLineWidth'
     */
    @Test
    public void absoluteAnnotationLineWidthTest() {
        // TODO: test absoluteAnnotationLineWidth
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

}
