/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PassportPDFPassport
 */
public class PassportPDFPassportTest {
    private final PassportPDFPassport model = new PassportPDFPassport();

    /**
     * Model tests for PassportPDFPassport
     */
    @Test
    public void testPassportPDFPassport() {
        // TODO: test PassportPDFPassport
    }

    /**
     * Test the property 'passportId'
     */
    @Test
    public void passportIdTest() {
        // TODO: test passportId
    }

    /**
     * Test the property 'planId'
     */
    @Test
    public void planIdTest() {
        // TODO: test planId
    }

    /**
     * Test the property 'optionalLinkedSubscriptionId'
     */
    @Test
    public void optionalLinkedSubscriptionIdTest() {
        // TODO: test optionalLinkedSubscriptionId
    }

    /**
     * Test the property 'subscriptionDate'
     */
    @Test
    public void subscriptionDateTest() {
        // TODO: test subscriptionDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'currentTokensUsed'
     */
    @Test
    public void currentTokensUsedTest() {
        // TODO: test currentTokensUsed
    }

    /**
     * Test the property 'extraTokens'
     */
    @Test
    public void extraTokensTest() {
        // TODO: test extraTokens
    }

    /**
     * Test the property 'extraTokensEndDate'
     */
    @Test
    public void extraTokensEndDateTest() {
        // TODO: test extraTokensEndDate
    }

    /**
     * Test the property 'isYearlyPaid'
     */
    @Test
    public void isYearlyPaidTest() {
        // TODO: test isYearlyPaid
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'tokensPercentUsageAlert'
     */
    @Test
    public void tokensPercentUsageAlertTest() {
        // TODO: test tokensPercentUsageAlert
    }

    /**
     * Test the property 'tokensPercentUsageAlertSent'
     */
    @Test
    public void tokensPercentUsageAlertSentTest() {
        // TODO: test tokensPercentUsageAlertSent
    }

    /**
     * Test the property 'isManaged'
     */
    @Test
    public void isManagedTest() {
        // TODO: test isManaged
    }

    /**
     * Test the property 'nextMonthlyTerm'
     */
    @Test
    public void nextMonthlyTermTest() {
        // TODO: test nextMonthlyTerm
    }

    /**
     * Test the property 'remainingTokens'
     */
    @Test
    public void remainingTokensTest() {
        // TODO: test remainingTokens
    }

}
