/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DrawableContentLayoutParameters;
import org.openapitools.client.model.PdfAlignedTextParameters;
import org.openapitools.client.model.SignatureCertificationLevel;
import org.openapitools.client.model.SignatureHash;
import org.openapitools.client.model.SignatureMode;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfDigiSignParameters
 */
public class PdfDigiSignParametersTest {
    private final PdfDigiSignParameters model = new PdfDigiSignParameters();

    /**
     * Model tests for PdfDigiSignParameters
     */
    @Test
    public void testPdfDigiSignParameters() {
        // TODO: test PdfDigiSignParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'certificateData'
     */
    @Test
    public void certificateDataTest() {
        // TODO: test certificateData
    }

    /**
     * Test the property 'certificatePassword'
     */
    @Test
    public void certificatePasswordTest() {
        // TODO: test certificatePassword
    }

    /**
     * Test the property 'signatureMode'
     */
    @Test
    public void signatureModeTest() {
        // TODO: test signatureMode
    }

    /**
     * Test the property 'signatureCertificationLevel'
     */
    @Test
    public void signatureCertificationLevelTest() {
        // TODO: test signatureCertificationLevel
    }

    /**
     * Test the property 'signatureHashAlgorithm'
     */
    @Test
    public void signatureHashAlgorithmTest() {
        // TODO: test signatureHashAlgorithm
    }

    /**
     * Test the property 'signerName'
     */
    @Test
    public void signerNameTest() {
        // TODO: test signerName
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'contactInfo'
     */
    @Test
    public void contactInfoTest() {
        // TODO: test contactInfo
    }

    /**
     * Test the property 'timeStampURL'
     */
    @Test
    public void timeStampURLTest() {
        // TODO: test timeStampURL
    }

    /**
     * Test the property 'timeStampUserName'
     */
    @Test
    public void timeStampUserNameTest() {
        // TODO: test timeStampUserName
    }

    /**
     * Test the property 'timeStampPassword'
     */
    @Test
    public void timeStampPasswordTest() {
        // TODO: test timeStampPassword
    }

    /**
     * Test the property 'linearize'
     */
    @Test
    public void linearizeTest() {
        // TODO: test linearize
    }

    /**
     * Test the property 'drawSignature'
     */
    @Test
    public void drawSignatureTest() {
        // TODO: test drawSignature
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'showValidationMark'
     */
    @Test
    public void showValidationMarkTest() {
        // TODO: test showValidationMark
    }

    /**
     * Test the property 'imageData'
     */
    @Test
    public void imageDataTest() {
        // TODO: test imageData
    }

    /**
     * Test the property 'signatureLayout'
     */
    @Test
    public void signatureLayoutTest() {
        // TODO: test signatureLayout
    }

    /**
     * Test the property 'signatureText'
     */
    @Test
    public void signatureTextTest() {
        // TODO: test signatureText
    }

}
