/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DrawableContentLayoutParameters;
import org.openapitools.client.model.PageNumberFormat;
import org.openapitools.client.model.PdfAlignedTextParameters;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfInsertPageNumberParameters
 */
public class PdfInsertPageNumberParametersTest {
    private final PdfInsertPageNumberParameters model = new PdfInsertPageNumberParameters();

    /**
     * Model tests for PdfInsertPageNumberParameters
     */
    @Test
    public void testPdfInsertPageNumberParameters() {
        // TODO: test PdfInsertPageNumberParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'pageRange'
     */
    @Test
    public void pageRangeTest() {
        // TODO: test pageRange
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'layout'
     */
    @Test
    public void layoutTest() {
        // TODO: test layout
    }

    /**
     * Test the property 'textParameters'
     */
    @Test
    public void textParametersTest() {
        // TODO: test textParameters
    }

}
