/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfLinearizeParameters
 */
public class PdfLinearizeParametersTest {
    private final PdfLinearizeParameters model = new PdfLinearizeParameters();

    /**
     * Model tests for PdfLinearizeParameters
     */
    @Test
    public void testPdfLinearizeParameters() {
        // TODO: test PdfLinearizeParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'packDocument'
     */
    @Test
    public void packDocumentTest() {
        // TODO: test packDocument
    }

}
