/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ScanMode;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfReadBarcodesParameters
 */
public class PdfReadBarcodesParametersTest {
    private final PdfReadBarcodesParameters model = new PdfReadBarcodesParameters();

    /**
     * Model tests for PdfReadBarcodesParameters
     */
    @Test
    public void testPdfReadBarcodesParameters() {
        // TODO: test PdfReadBarcodesParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'pageRange'
     */
    @Test
    public void pageRangeTest() {
        // TODO: test pageRange
    }

    /**
     * Test the property 'scanMode'
     */
    @Test
    public void scanModeTest() {
        // TODO: test scanMode
    }

    /**
     * Test the property 'scanBarcode1D'
     */
    @Test
    public void scanBarcode1DTest() {
        // TODO: test scanBarcode1D
    }

    /**
     * Test the property 'scanBarcodeQR'
     */
    @Test
    public void scanBarcodeQRTest() {
        // TODO: test scanBarcodeQR
    }

    /**
     * Test the property 'scanBarcodeMicroQR'
     */
    @Test
    public void scanBarcodeMicroQRTest() {
        // TODO: test scanBarcodeMicroQR
    }

    /**
     * Test the property 'scanBarcodePDF417'
     */
    @Test
    public void scanBarcodePDF417Test() {
        // TODO: test scanBarcodePDF417
    }

    /**
     * Test the property 'scanBarcodeDataMatrix'
     */
    @Test
    public void scanBarcodeDataMatrixTest() {
        // TODO: test scanBarcodeDataMatrix
    }

    /**
     * Test the property 'scanBarcodeAztec'
     */
    @Test
    public void scanBarcodeAztecTest() {
        // TODO: test scanBarcodeAztec
    }

}
