/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfSaveAsJPEGParameters
 */
public class PdfSaveAsJPEGParametersTest {
    private final PdfSaveAsJPEGParameters model = new PdfSaveAsJPEGParameters();

    /**
     * Model tests for PdfSaveAsJPEGParameters
     */
    @Test
    public void testPdfSaveAsJPEGParameters() {
        // TODO: test PdfSaveAsJPEGParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'pageRange'
     */
    @Test
    public void pageRangeTest() {
        // TODO: test pageRange
    }

    /**
     * Test the property 'quality'
     */
    @Test
    public void qualityTest() {
        // TODO: test quality
    }

    /**
     * Test the property 'progressive'
     */
    @Test
    public void progressiveTest() {
        // TODO: test progressive
    }

    /**
     * Test the property 'resolution'
     */
    @Test
    public void resolutionTest() {
        // TODO: test resolution
    }

    /**
     * Test the property 'renderFormFields'
     */
    @Test
    public void renderFormFieldsTest() {
        // TODO: test renderFormFields
    }

    /**
     * Test the property 'keepRasterPDFResolution'
     */
    @Test
    public void keepRasterPDFResolutionTest() {
        // TODO: test keepRasterPDFResolution
    }

}
