/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.PdfPageBox;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfSetPageBoxParameters
 */
public class PdfSetPageBoxParametersTest {
    private final PdfSetPageBoxParameters model = new PdfSetPageBoxParameters();

    /**
     * Model tests for PdfSetPageBoxParameters
     */
    @Test
    public void testPdfSetPageBoxParameters() {
        // TODO: test PdfSetPageBoxParameters
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'pageRange'
     */
    @Test
    public void pageRangeTest() {
        // TODO: test pageRange
    }

    /**
     * Test the property 'left'
     */
    @Test
    public void leftTest() {
        // TODO: test left
    }

    /**
     * Test the property 'top'
     */
    @Test
    public void topTest() {
        // TODO: test top
    }

    /**
     * Test the property 'right'
     */
    @Test
    public void rightTest() {
        // TODO: test right
    }

    /**
     * Test the property 'bottom'
     */
    @Test
    public void bottomTest() {
        // TODO: test bottom
    }

    /**
     * Test the property 'pageBox'
     */
    @Test
    public void pageBoxTest() {
        // TODO: test pageBox
    }

}
