/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.FontStyle;
import org.openapitools.client.model.StandardFontName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PdfTextParameters
 */
public class PdfTextParametersTest {
    private final PdfTextParameters model = new PdfTextParameters();

    /**
     * Model tests for PdfTextParameters
     */
    @Test
    public void testPdfTextParameters() {
        // TODO: test PdfTextParameters
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'textColor'
     */
    @Test
    public void textColorTest() {
        // TODO: test textColor
    }

    /**
     * Test the property 'fontName'
     */
    @Test
    public void fontNameTest() {
        // TODO: test fontName
    }

    /**
     * Test the property 'standardFontName'
     */
    @Test
    public void standardFontNameTest() {
        // TODO: test standardFontName
    }

    /**
     * Test the property 'fontStyle'
     */
    @Test
    public void fontStyleTest() {
        // TODO: test fontStyle
    }

    /**
     * Test the property 'fontSize'
     */
    @Test
    public void fontSizeTest() {
        // TODO: test fontSize
    }

}
