/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ContentSize;
import org.openapitools.client.model.DrawableContentLayoutParameters;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SquareAndCircleAnnotationParameters
 */
public class SquareAndCircleAnnotationParametersTest {
    private final SquareAndCircleAnnotationParameters model = new SquareAndCircleAnnotationParameters();

    /**
     * Model tests for SquareAndCircleAnnotationParameters
     */
    @Test
    public void testSquareAndCircleAnnotationParameters() {
        // TODO: test SquareAndCircleAnnotationParameters
    }

    /**
     * Test the property 'annotationLayout'
     */
    @Test
    public void annotationLayoutTest() {
        // TODO: test annotationLayout
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'lineWidth'
     */
    @Test
    public void lineWidthTest() {
        // TODO: test lineWidth
    }

    /**
     * Test the property 'absoluteAnnotationLineWidth'
     */
    @Test
    public void absoluteAnnotationLineWidthTest() {
        // TODO: test absoluteAnnotationLineWidth
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

}
