/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DrawableContentLayoutParameters;
import org.openapitools.client.model.StickyNoteAnnotationIcon;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StickyNoteAnnotationParameters
 */
public class StickyNoteAnnotationParametersTest {
    private final StickyNoteAnnotationParameters model = new StickyNoteAnnotationParameters();

    /**
     * Model tests for StickyNoteAnnotationParameters
     */
    @Test
    public void testStickyNoteAnnotationParameters() {
        // TODO: test StickyNoteAnnotationParameters
    }

    /**
     * Test the property 'annotationLayout'
     */
    @Test
    public void annotationLayoutTest() {
        // TODO: test annotationLayout
    }

    /**
     * Test the property 'stickyNoteIcon'
     */
    @Test
    public void stickyNoteIconTest() {
        // TODO: test stickyNoteIcon
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'openPopup'
     */
    @Test
    public void openPopupTest() {
        // TODO: test openPopup
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

}
