/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.FontStyle;

/**
 * Represents a font.
 */
@ApiModel(description = "Represents a font.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-27T13:23:36.328+02:00[Europe/Paris]")
public class Font {
  public static final String SERIALIZED_NAME_FONT_STYLE = "FontStyle";
  @SerializedName(SERIALIZED_NAME_FONT_STYLE)
  private FontStyle fontStyle;

  public static final String SERIALIZED_NAME_FAMILY_NAME = "FamilyName";
  @SerializedName(SERIALIZED_NAME_FAMILY_NAME)
  private String familyName;


  public Font fontStyle(FontStyle fontStyle) {
    
    this.fontStyle = fontStyle;
    return this;
  }

   /**
   * Get fontStyle
   * @return fontStyle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FontStyle getFontStyle() {
    return fontStyle;
  }


  public void setFontStyle(FontStyle fontStyle) {
    this.fontStyle = fontStyle;
  }


  public Font familyName(String familyName) {
    
    this.familyName = familyName;
    return this;
  }

   /**
   * Specifies the family name of the font, i.e: \&quot;Arial\&quot;.
   * @return familyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the family name of the font, i.e: \"Arial\".")

  public String getFamilyName() {
    return familyName;
  }


  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Font font = (Font) o;
    return Objects.equals(this.fontStyle, font.fontStyle) &&
        Objects.equals(this.familyName, font.familyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fontStyle, familyName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Font {\n");
    sb.append("    fontStyle: ").append(toIndentedString(fontStyle)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

