/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents the parameters for a detect page orientation action.
 */
@ApiModel(description = "Represents the parameters for a detect page orientation action.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-27T13:23:36.328+02:00[Europe/Paris]")
public class ImageDetectPageOrientationParameters {
  public static final String SERIALIZED_NAME_FILE_ID = "FileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_PAGE_RANGE = "PageRange";
  @SerializedName(SERIALIZED_NAME_PAGE_RANGE)
  private String pageRange;

  public static final String SERIALIZED_NAME_LANGUAGE = "Language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language = "eng";

  public static final String SERIALIZED_NAME_AUTOMATICALLY_APPLY_ROTATION = "AutomaticallyApplyRotation";
  @SerializedName(SERIALIZED_NAME_AUTOMATICALLY_APPLY_ROTATION)
  private Boolean automaticallyApplyRotation = true;


  public ImageDetectPageOrientationParameters fileId(String fileId) {
    
    this.fileId = fileId;
    return this;
  }

   /**
   * The identifier of the previously uploaded file to be processed.
   * @return fileId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the previously uploaded file to be processed.")

  public String getFileId() {
    return fileId;
  }


  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  public ImageDetectPageOrientationParameters pageRange(String pageRange) {
    
    this.pageRange = pageRange;
    return this;
  }

   /**
   * Specifies the number of the page, or the range of pages to be processed.
   * @return pageRange
  **/
  @ApiModelProperty(required = true, value = "Specifies the number of the page, or the range of pages to be processed.")

  public String getPageRange() {
    return pageRange;
  }


  public void setPageRange(String pageRange) {
    this.pageRange = pageRange;
  }


  public ImageDetectPageOrientationParameters language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Specifies the language(s) to be used for the OCR.
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the language(s) to be used for the OCR.")

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public ImageDetectPageOrientationParameters automaticallyApplyRotation(Boolean automaticallyApplyRotation) {
    
    this.automaticallyApplyRotation = automaticallyApplyRotation;
    return this;
  }

   /**
   * Specifies whether a rotation shall be automatically applied in order to correct the page orientation when needed.
   * @return automaticallyApplyRotation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies whether a rotation shall be automatically applied in order to correct the page orientation when needed.")

  public Boolean getAutomaticallyApplyRotation() {
    return automaticallyApplyRotation;
  }


  public void setAutomaticallyApplyRotation(Boolean automaticallyApplyRotation) {
    this.automaticallyApplyRotation = automaticallyApplyRotation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageDetectPageOrientationParameters imageDetectPageOrientationParameters = (ImageDetectPageOrientationParameters) o;
    return Objects.equals(this.fileId, imageDetectPageOrientationParameters.fileId) &&
        Objects.equals(this.pageRange, imageDetectPageOrientationParameters.pageRange) &&
        Objects.equals(this.language, imageDetectPageOrientationParameters.language) &&
        Objects.equals(this.automaticallyApplyRotation, imageDetectPageOrientationParameters.automaticallyApplyRotation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, pageRange, language, automaticallyApplyRotation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageDetectPageOrientationParameters {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    pageRange: ").append(toIndentedString(pageRange)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    automaticallyApplyRotation: ").append(toIndentedString(automaticallyApplyRotation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

