/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Defines the supported types of Link Annotation.
 */
@JsonAdapter(LinkAnnotationType.Adapter.class)
public enum LinkAnnotationType {
  
  PAGE("Page"),
  
  WEB("Web");

  private String value;

  LinkAnnotationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LinkAnnotationType fromValue(String value) {
    for (LinkAnnotationType b : LinkAnnotationType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LinkAnnotationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LinkAnnotationType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LinkAnnotationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LinkAnnotationType.fromValue(value);
    }
  }
}

