/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents the parameters for an auto deskew action.
 */
@ApiModel(description = "Represents the parameters for an auto deskew action.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-27T13:23:36.328+02:00[Europe/Paris]")
public class PdfAutoDeskewParameters {
  public static final String SERIALIZED_NAME_FILE_ID = "FileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_PAGE_RANGE = "PageRange";
  @SerializedName(SERIALIZED_NAME_PAGE_RANGE)
  private String pageRange;

  public static final String SERIALIZED_NAME_MAX_ANGLE_OF_RESEARCH = "MaxAngleOfResearch";
  @SerializedName(SERIALIZED_NAME_MAX_ANGLE_OF_RESEARCH)
  private Float maxAngleOfResearch = 15f;

  public static final String SERIALIZED_NAME_OPTIMISTIC = "Optimistic";
  @SerializedName(SERIALIZED_NAME_OPTIMISTIC)
  private Boolean optimistic = false;


  public PdfAutoDeskewParameters fileId(String fileId) {
    
    this.fileId = fileId;
    return this;
  }

   /**
   * The identifier of the previously uploaded file to be processed.
   * @return fileId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the previously uploaded file to be processed.")

  public String getFileId() {
    return fileId;
  }


  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  public PdfAutoDeskewParameters pageRange(String pageRange) {
    
    this.pageRange = pageRange;
    return this;
  }

   /**
   * Specifies the page or the page range to be auto-deskewed.
   * @return pageRange
  **/
  @ApiModelProperty(required = true, value = "Specifies the page or the page range to be auto-deskewed.")

  public String getPageRange() {
    return pageRange;
  }


  public void setPageRange(String pageRange) {
    this.pageRange = pageRange;
  }


  public PdfAutoDeskewParameters maxAngleOfResearch(Float maxAngleOfResearch) {
    
    this.maxAngleOfResearch = maxAngleOfResearch;
    return this;
  }

   /**
   * Specifies the maximum skew angle to be detected. A value of below 15 is suggested.
   * @return maxAngleOfResearch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the maximum skew angle to be detected. A value of below 15 is suggested.")

  public Float getMaxAngleOfResearch() {
    return maxAngleOfResearch;
  }


  public void setMaxAngleOfResearch(Float maxAngleOfResearch) {
    this.maxAngleOfResearch = maxAngleOfResearch;
  }


  public PdfAutoDeskewParameters optimistic(Boolean optimistic) {
    
    this.optimistic = optimistic;
    return this;
  }

   /**
   * Specifies whether the skew detection engine must be optimistic when detecting angles.  If you know the image is skewed, you should set this to true.
   * @return optimistic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies whether the skew detection engine must be optimistic when detecting angles.  If you know the image is skewed, you should set this to true.")

  public Boolean getOptimistic() {
    return optimistic;
  }


  public void setOptimistic(Boolean optimistic) {
    this.optimistic = optimistic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfAutoDeskewParameters pdfAutoDeskewParameters = (PdfAutoDeskewParameters) o;
    return Objects.equals(this.fileId, pdfAutoDeskewParameters.fileId) &&
        Objects.equals(this.pageRange, pdfAutoDeskewParameters.pageRange) &&
        Objects.equals(this.maxAngleOfResearch, pdfAutoDeskewParameters.maxAngleOfResearch) &&
        Objects.equals(this.optimistic, pdfAutoDeskewParameters.optimistic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, pageRange, maxAngleOfResearch, optimistic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfAutoDeskewParameters {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    pageRange: ").append(toIndentedString(pageRange)).append("\n");
    sb.append("    maxAngleOfResearch: ").append(toIndentedString(maxAngleOfResearch)).append("\n");
    sb.append("    optimistic: ").append(toIndentedString(optimistic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

