/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents the parameters for an extract page action.
 */
@ApiModel(description = "Represents the parameters for an extract page action.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-27T13:23:36.328+02:00[Europe/Paris]")
public class PdfExtractPageParameters {
  public static final String SERIALIZED_NAME_FILE_ID = "FileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_PAGE_RANGE = "PageRange";
  @SerializedName(SERIALIZED_NAME_PAGE_RANGE)
  private String pageRange;

  public static final String SERIALIZED_NAME_EXTRACT_AS_SEPARATE = "ExtractAsSeparate";
  @SerializedName(SERIALIZED_NAME_EXTRACT_AS_SEPARATE)
  private Boolean extractAsSeparate = false;

  public static final String SERIALIZED_NAME_IMMEDIATE_DOWNLOAD = "ImmediateDownload";
  @SerializedName(SERIALIZED_NAME_IMMEDIATE_DOWNLOAD)
  private Boolean immediateDownload = false;


  public PdfExtractPageParameters fileId(String fileId) {
    
    this.fileId = fileId;
    return this;
  }

   /**
   * The identifier of the previously uploaded file to be processed.
   * @return fileId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the previously uploaded file to be processed.")

  public String getFileId() {
    return fileId;
  }


  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  public PdfExtractPageParameters pageRange(String pageRange) {
    
    this.pageRange = pageRange;
    return this;
  }

   /**
   * Specifies the number of the page, or the range of pages to be extracted.
   * @return pageRange
  **/
  @ApiModelProperty(required = true, value = "Specifies the number of the page, or the range of pages to be extracted.")

  public String getPageRange() {
    return pageRange;
  }


  public void setPageRange(String pageRange) {
    this.pageRange = pageRange;
  }


  public PdfExtractPageParameters extractAsSeparate(Boolean extractAsSeparate) {
    
    this.extractAsSeparate = extractAsSeparate;
    return this;
  }

   /**
   * Specifies whether each extracted page shall form a separate document.
   * @return extractAsSeparate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies whether each extracted page shall form a separate document.")

  public Boolean getExtractAsSeparate() {
    return extractAsSeparate;
  }


  public void setExtractAsSeparate(Boolean extractAsSeparate) {
    this.extractAsSeparate = extractAsSeparate;
  }


  public PdfExtractPageParameters immediateDownload(Boolean immediateDownload) {
    
    this.immediateDownload = immediateDownload;
    return this;
  }

   /**
   * Specifies whether the file(s) created as a result of the action shall be available for immediate download.
   * @return immediateDownload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies whether the file(s) created as a result of the action shall be available for immediate download.")

  public Boolean getImmediateDownload() {
    return immediateDownload;
  }


  public void setImmediateDownload(Boolean immediateDownload) {
    this.immediateDownload = immediateDownload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfExtractPageParameters pdfExtractPageParameters = (PdfExtractPageParameters) o;
    return Objects.equals(this.fileId, pdfExtractPageParameters.fileId) &&
        Objects.equals(this.pageRange, pdfExtractPageParameters.pageRange) &&
        Objects.equals(this.extractAsSeparate, pdfExtractPageParameters.extractAsSeparate) &&
        Objects.equals(this.immediateDownload, pdfExtractPageParameters.immediateDownload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, pageRange, extractAsSeparate, immediateDownload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfExtractPageParameters {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    pageRange: ").append(toIndentedString(pageRange)).append("\n");
    sb.append("    extractAsSeparate: ").append(toIndentedString(extractAsSeparate)).append("\n");
    sb.append("    immediateDownload: ").append(toIndentedString(immediateDownload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

