/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents the parameters for a scale page action.
 */
@ApiModel(description = "Represents the parameters for a scale page action.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-27T13:23:36.328+02:00[Europe/Paris]")
public class PdfScalePageParameters {
  public static final String SERIALIZED_NAME_FILE_ID = "FileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_PAGE_RANGE = "PageRange";
  @SerializedName(SERIALIZED_NAME_PAGE_RANGE)
  private String pageRange;

  public static final String SERIALIZED_NAME_SCALE_X = "ScaleX";
  @SerializedName(SERIALIZED_NAME_SCALE_X)
  private Float scaleX;

  public static final String SERIALIZED_NAME_SCALE_Y = "ScaleY";
  @SerializedName(SERIALIZED_NAME_SCALE_Y)
  private Float scaleY;


  public PdfScalePageParameters fileId(String fileId) {
    
    this.fileId = fileId;
    return this;
  }

   /**
   * The identifier of the previously uploaded file to be processed.
   * @return fileId
  **/
  @ApiModelProperty(required = true, value = "The identifier of the previously uploaded file to be processed.")

  public String getFileId() {
    return fileId;
  }


  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  public PdfScalePageParameters pageRange(String pageRange) {
    
    this.pageRange = pageRange;
    return this;
  }

   /**
   * Specifies the number of the page, or the range of pages which shall be scaled.
   * @return pageRange
  **/
  @ApiModelProperty(required = true, value = "Specifies the number of the page, or the range of pages which shall be scaled.")

  public String getPageRange() {
    return pageRange;
  }


  public void setPageRange(String pageRange) {
    this.pageRange = pageRange;
  }


  public PdfScalePageParameters scaleX(Float scaleX) {
    
    this.scaleX = scaleX;
    return this;
  }

   /**
   * Specifies the horizontal scale factor, by which the width of the page shall be multiplied.
   * @return scaleX
  **/
  @ApiModelProperty(required = true, value = "Specifies the horizontal scale factor, by which the width of the page shall be multiplied.")

  public Float getScaleX() {
    return scaleX;
  }


  public void setScaleX(Float scaleX) {
    this.scaleX = scaleX;
  }


  public PdfScalePageParameters scaleY(Float scaleY) {
    
    this.scaleY = scaleY;
    return this;
  }

   /**
   * Specifies the horizontal scale factor, by which the height of the page shall be multiplied.
   * @return scaleY
  **/
  @ApiModelProperty(required = true, value = "Specifies the horizontal scale factor, by which the height of the page shall be multiplied.")

  public Float getScaleY() {
    return scaleY;
  }


  public void setScaleY(Float scaleY) {
    this.scaleY = scaleY;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfScalePageParameters pdfScalePageParameters = (PdfScalePageParameters) o;
    return Objects.equals(this.fileId, pdfScalePageParameters.fileId) &&
        Objects.equals(this.pageRange, pdfScalePageParameters.pageRange) &&
        Objects.equals(this.scaleX, pdfScalePageParameters.scaleX) &&
        Objects.equals(this.scaleY, pdfScalePageParameters.scaleY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, pageRange, scaleX, scaleY);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfScalePageParameters {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    pageRange: ").append(toIndentedString(pageRange)).append("\n");
    sb.append("    scaleX: ").append(toIndentedString(scaleX)).append("\n");
    sb.append("    scaleY: ").append(toIndentedString(scaleY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

