/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ReduceErrorCode;

/**
 * Represents information about an error which caused the failure of a reduce action.
 */
@ApiModel(description = "Represents information about an error which caused the failure of a reduce action.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-27T13:23:36.328+02:00[Europe/Paris]")
public class ReduceErrorInfo {
  public static final String SERIALIZED_NAME_ERROR_CODE = "ErrorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  private ReduceErrorCode errorCode;

  public static final String SERIALIZED_NAME_PAGE_NUMBER = "PageNumber";
  @SerializedName(SERIALIZED_NAME_PAGE_NUMBER)
  private Integer pageNumber;

  public static final String SERIALIZED_NAME_EXT_ERROR_MESSAGE = "ExtErrorMessage";
  @SerializedName(SERIALIZED_NAME_EXT_ERROR_MESSAGE)
  private String extErrorMessage;


  public ReduceErrorInfo errorCode(ReduceErrorCode errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReduceErrorCode getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(ReduceErrorCode errorCode) {
    this.errorCode = errorCode;
  }


   /**
   * The number of the page processed when the error occured.
   * @return pageNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of the page processed when the error occured.")

  public Integer getPageNumber() {
    return pageNumber;
  }




   /**
   * The error message associated with the error, if any.
   * @return extErrorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The error message associated with the error, if any.")

  public String getExtErrorMessage() {
    return extErrorMessage;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReduceErrorInfo reduceErrorInfo = (ReduceErrorInfo) o;
    return Objects.equals(this.errorCode, reduceErrorInfo.errorCode) &&
        Objects.equals(this.pageNumber, reduceErrorInfo.pageNumber) &&
        Objects.equals(this.extErrorMessage, reduceErrorInfo.extErrorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, pageNumber, extErrorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReduceErrorInfo {\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    extErrorMessage: ").append(toIndentedString(extErrorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

