/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Specifies the level of the signature certification.
 */
@JsonAdapter(SignatureCertificationLevel.Adapter.class)
public enum SignatureCertificationLevel {
  
  NOTCERTIFIED("NotCertified"),
  
  NOCHANGES("NoChanges"),
  
  FORMFILLING("FormFilling"),
  
  FORMFILLINGANDANNOTATIONS("FormFillingAndAnnotations");

  private String value;

  SignatureCertificationLevel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SignatureCertificationLevel fromValue(String value) {
    for (SignatureCertificationLevel b : SignatureCertificationLevel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SignatureCertificationLevel> {
    @Override
    public void write(final JsonWriter jsonWriter, final SignatureCertificationLevel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SignatureCertificationLevel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SignatureCertificationLevel.fromValue(value);
    }
  }
}

