/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Defines the different available standard fonts (Standard Type 1) which can be used without prior definition.
 */
@JsonAdapter(StandardFontName.Adapter.class)
public enum StandardFontName {
  
  COURIER("Courier"),
  
  HELVETICA("Helvetica"),
  
  TIMES("Times"),
  
  SYMBOL("Symbol"),
  
  ZAPFDINGBATS("ZapfDingbats");

  private String value;

  StandardFontName(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static StandardFontName fromValue(String value) {
    for (StandardFontName b : StandardFontName.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<StandardFontName> {
    @Override
    public void write(final JsonWriter jsonWriter, final StandardFontName enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public StandardFontName read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return StandardFontName.fromValue(value);
    }
  }
}

