/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Font;
import org.openapitools.client.model.IntegerResponse;
import org.openapitools.client.model.LongResponse;
import org.openapitools.client.model.StringArrayResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigApi
 */
@Ignore
public class ConfigApiTest {

    private final ConfigApi api = new ConfigApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configGetAPIVersionTest() throws ApiException {
        String response = api.configGetAPIVersion();

        // TODO: test validations
    }
    
    /**
     * Gets the maximal length of a request content, in bytes.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configGetMaxAllowedContentLengthTest() throws ApiException {
        LongResponse response = api.configGetMaxAllowedContentLength();

        // TODO: test validations
    }
    
    /**
     * Gets the suggested client API timeout, in milliseconds.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configGetSuggestedClientTimeoutTest() throws ApiException {
        IntegerResponse response = api.configGetSuggestedClientTimeout();

        // TODO: test validations
    }
    
    /**
     * Gets the suggested maximum number of threads to be used simultaneously by a client application.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configGetSuggestedMaxClientThreadsTest() throws ApiException {
        IntegerResponse response = api.configGetSuggestedMaxClientThreads();

        // TODO: test validations
    }
    
    /**
     * Gets the list of supported fonts for text drawing operations.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configGetSupportedFontsTest() throws ApiException {
        List<Font> response = api.configGetSupportedFonts();

        // TODO: test validations
    }
    
    /**
     * Gets the list of supported languages for OCR.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configGetSupportedOCRLanguagesTest() throws ApiException {
        StringArrayResponse response = api.configGetSupportedOCRLanguages();

        // TODO: test validations
    }
    
}
