/*
 * PassportPDF API
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PassportPDFPassport;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PassportManagerApi
 */
@Ignore
public class PassportManagerApiTest {

    private final PassportManagerApi api = new PassportManagerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void passportManagerGetPassportInfoTest() throws ApiException {
        String passportId = null;
        PassportPDFPassport response = api.passportManagerGetPassportInfo(passportId);

        // TODO: test validations
    }
    
}
